In [1]:
from weak_stage_utils import *

# First, we do training using the weak labelled dataset PQA-A

weak_path = "../Preprocessing+baseline/data/ori_pqaa.json"

full_split_save_path = "./data"

tokenizer = get_tokenizer()

weak_dataset = load_weak_json(weak_path)
validate_weak_dataset(weak_dataset)

weak_dataset = weak_dataset.map(add_binary_label)

full_split = build_full_split(weak_dataset, val_size=0.1, seed=7)
save_dataset_split(full_split, full_split_save_path)

pilot_split = build_pilot_split(full_split, pilot_fraction=0.05, seed=7)

print_split_summary(full_split, title="FULL WEAK DATASET (90/10 Train/dev split)")
print_split_summary(pilot_split, title="PILOT WEAK SPLIT (90/10 Train/dev split)")

tokenized_pilot = tokenize_split(pilot_split, tokenizer=tokenizer, max_length=512)

pilot_class_weights = build_class_weights(tokenized_pilot["train"])
pilot_sample_weights = build_sample_weights(tokenized_pilot["train"])

========================================================================================
WEAK DATA CHECK
========================================================================================
Examples      : 211269
Label counts  : {'yes': 196144, 'no': 15125}
Unique labels : ['no', 'yes']

Map:   0%|          | 0/211269 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/190142 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/21127 [00:00<?, ? examples/s]

========================================================================================
FULL WEAK DATASET (90/10 Train/dev split)
========================================================================================
train examples : 190142
train label counts : {'no': 13641, 'yes': 176501}

validation examples : 21127
validation label counts : {'no': 1484, 'yes': 19643}


========================================================================================
PILOT WEAK SPLIT (90/10 Train/dev split)
========================================================================================
train examples : 9507
train label counts : {'no': 677, 'yes': 8830}

validation examples : 1056
validation label counts : {'no': 67, 'yes': 989}

Map:   0%|          | 0/9507 [00:00<?, ? examples/s]

Map:   0%|          | 0/1056 [00:00<?, ? examples/s]

In [2]:
#First pilot stage

print_stage_header(
    "WEAK TRAINING PILOT",
    (
        "Cheap pilot on 10 percent of the PQA-A Dataset. "
        "Goal is to choose the best imbalance-handling method before full weak training."
    ),
)

pilot_configs = [
    {
        "run_name": "weak_pilot_plain",
        "learning_rate": 1e-5,
        "num_train_epochs": 4,
        "train_batch_size": 8,
        "eval_batch_size": 8,
        "gradient_accumulation_steps": 2,
        "use_weighted_loss": False,
        "use_weighted_sampler": False,
    },
    {
        "run_name": "weak_pilot_weighted_loss",
        "learning_rate": 1e-5,
        "num_train_epochs": 4,
        "train_batch_size": 8,
        "eval_batch_size": 8,
        "gradient_accumulation_steps": 2,
        "use_weighted_loss": True,
        "use_weighted_sampler": False,
    },
    {
        "run_name": "weak_pilot_weighted_sampler",
        "learning_rate": 1e-5,
        "num_train_epochs": 4,
        "train_batch_size": 8,
        "eval_batch_size": 8,
        "gradient_accumulation_steps": 2,
        "use_weighted_loss": False,
        "use_weighted_sampler": True,
    },
    {
        "run_name": "weak_pilot_loss_plus_sampler",
        "learning_rate": 1e-5,
        "num_train_epochs": 4,
        "train_batch_size": 8,
        "eval_batch_size": 8,
        "gradient_accumulation_steps": 2,
        "use_weighted_loss": True,
        "use_weighted_sampler": True,
    },
]

pilot_results = []

for cfg in pilot_configs:
    result = run_weak_experiment(
        tokenized_split=tokenized_pilot,
        tokenizer=tokenizer,
        class_weights=pilot_class_weights,
        sample_weights=pilot_sample_weights,
        seed=7,
        **cfg,
    )
    pilot_results.append(result)

print_results_table(pilot_results, "PILOT RESULTS")

best_pilot = choose_best_result(pilot_results, key="macro_f1")

print()
print("Best pilot setup")
print(best_pilot["run_name"])
print(best_pilot["final_metrics"])

========================================================================================
WEAK TRAINING PILOT
========================================================================================
Cheap pilot on 10 percent of the PQA-A Dataset. Goal is to choose the best imbalance-handling method before full weak training.

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

========================================================================================
PILOT RESULTS
========================================================================================
weak_pilot_plain | acc=0.9669 | macro_f1=0.8489 | f1_no=0.7154 | f1_yes=0.9824 | loss=False | sampler=False
weak_pilot_weighted_loss | acc=0.9640 | macro_f1=0.8372 | f1_no=0.6935 | f1_yes=0.9809 | loss=True | sampler=False
weak_pilot_weighted_sampler | acc=0.9659 | macro_f1=0.8525 | f1_no=0.7231 | f1_yes=0.9818 | loss=False | sampler=True
weak_pilot_loss_plus_sampler | acc=0.9593 | macro_f1=0.8172 | f1_no=0.6560 | f1_yes=0.9784 | loss=True | sampler=True

Best pilot setup
weak_pilot_weighted_sampler
{'accuracy': 0.9659090909090909, 'macro_f1': 0.8524567259178762, 'f1_no': 0.7230769230769231, 'f1_yes': 0.9818365287588294}

In [3]:
print_stage_header(
    "PILOT LR CHECK",
    (
        "Best method is now fixed. We now test one lower and one higher learning rate, "
        "then compare both against the existing best pilot with the base learning rate."
    ),
)

base_lr = best_pilot["learning_rate"]

extra_lr_candidates = [
    ("lr_low", 8e-6),
    ("lr_high", 1.2e-5),
]

extra_lr_results = []

for lr_name, lr_value in extra_lr_candidates:
    result = run_weak_experiment(
        run_name=f"weak_pilot_weighted_sampler_{lr_name}",
        tokenized_split=tokenized_pilot,
        tokenizer=tokenizer,
        learning_rate=lr_value,
        num_train_epochs=4,
        train_batch_size=8,
        eval_batch_size=8,
        gradient_accumulation_steps=best_pilot["gradient_accumulation_steps"],
        class_weights=pilot_class_weights,
        sample_weights=pilot_sample_weights,
        use_weighted_loss=best_pilot["use_weighted_loss"],
        use_weighted_sampler=best_pilot["use_weighted_sampler"],
        seed=7,
    )
    extra_lr_results.append(result)

lr_comparison_results = [best_pilot] + extra_lr_results

print_results_table(lr_comparison_results, "PILOT LR RESULTS")

best_lr_result = choose_best_result(lr_comparison_results, key="macro_f1")

print()
print("Best LR after local pilot check")
print(best_lr_result["run_name"])
print(best_lr_result["final_metrics"])
print(f"Chosen learning rate for full weak training: {best_lr_result['learning_rate']}")

========================================================================================
PILOT LR CHECK
========================================================================================
Best method is now fixed. We now test one lower and one higher learning rate, then compare both against the existing best pilot with the base learning rate.

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

========================================================================================
PILOT LR RESULTS
========================================================================================
weak_pilot_weighted_sampler | acc=0.9659 | macro_f1=0.8525 | f1_no=0.7231 | f1_yes=0.9818 | loss=False | sampler=True
weak_pilot_weighted_sampler_lr_low | acc=0.9394 | macro_f1=0.7908 | f1_no=0.6145 | f1_yes=0.9671 | loss=False | sampler=True
weak_pilot_weighted_sampler_lr_high | acc=0.9602 | macro_f1=0.8372 | f1_no=0.6957 | f1_yes=0.9787 | loss=False | sampler=True

Best LR after local pilot check
weak_pilot_weighted_sampler
{'accuracy': 0.9659090909090909, 'macro_f1': 0.8524567259178762, 'f1_no': 0.7230769230769231, 'f1_yes': 0.9818365287588294}
Chosen learning rate for full weak training: 1e-05

In [6]:
# Now full stage
import importlib
import weak_stage_utils
importlib.reload(weak_stage_utils)
from weak_stage_utils import *

full_split = load_dataset_split(full_split_save_path)

tokenized_full = tokenize_split(full_split, tokenizer=tokenizer, max_length=512)

full_class_weights = build_class_weights(tokenized_full["train"])
full_sample_weights = build_sample_weights(tokenized_full["train"])

print_stage_header(
    "FULL DATASET WEAK TRAINING",
    (
        "Train on the full PQA-A dataset using the best pilot config. "
        "This exported model becomes the reusable warm-start checkpoint for all Stage 2 ablations."
    ),
)

full_run_result = run_weak_experiment(
    run_name="weak_full_best_method",
    tokenized_split=tokenized_full,
    tokenizer=tokenizer,
    learning_rate=best_lr_result["learning_rate"],
    num_train_epochs=6,
    train_batch_size=8,
    eval_batch_size=8,
    gradient_accumulation_steps=best_pilot["gradient_accumulation_steps"],
    class_weights=full_class_weights,
    sample_weights=full_sample_weights,
    use_weighted_loss=best_pilot["use_weighted_loss"],
    use_weighted_sampler=best_pilot["use_weighted_sampler"],
    seed=7,
)

print(full_run_result["final_metrics"])

Map:   0%|          | 0/190142 [00:00<?, ? examples/s]

Map:   0%|          | 0/21127 [00:00<?, ? examples/s]

========================================================================================
FULL DATASET WEAK TRAINING
========================================================================================
Train on the full PQA-A dataset using the best pilot config. This exported model becomes the reusable warm-start checkpoint for all Stage 2 ablations.

/Users/eduvieojoboh/Group-21-/BiomedBERTClinical/weak_stage_utils.py:323: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `WeakTrainer.__init__`. Use `processing_class` instead.
  super().__init__(*args, **kwargs)

{'accuracy': 0.9809722156482227, 'macro_f1': 0.9219793495450634, 'f1_no': 0.8541364296081277, 'f1_yes': 0.9898222694819991}

In [7]:
# Exporting best config to use for downstream fine-tuning
export_metadata = {
    "stage": "stage1_binary_weak_warmstart",
    "model_id": model_id,
    "label_to_id": label_to_id,
    "id_to_label": id_to_label,
    "max_length": 512,
    "truncation": "only_second",
    "split": "90_train_10_validation",
    "pilot_fraction": 0.05,
    "best_method_from_pilot": {
        "use_weighted_loss": best_pilot["use_weighted_loss"],
        "use_weighted_sampler": best_pilot["use_weighted_sampler"],
        "learning_rate": best_lr_result["learning_rate"],
        "gradient_accumulation_steps": best_pilot["gradient_accumulation_steps"],
    },
    "full_run_metrics": full_run_result["final_metrics"],
    "best_checkpoint": full_run_result["best_checkpoint"],
}

export_best_weak_model(
    best_checkpoint_path=full_run_result["best_checkpoint"],
    tokenizer=tokenizer,
    export_dir="./artifacts/stage1_binary_warmstart_best",
    metadata=export_metadata,
)

# Delete suboptimal runs
delete_non_best_run_dirs(
    results=pilot_results + extra_lr_results + [full_run_result],
    best_run_name="weak_full_best_method",
    runs_root="./weak_runs",
)