In [1]:
# paths + core config

from Stage2_expert_stage_utils import *

stage1_checkpoint_path = "./artifacts/stage1_binary_warmstart_best"
expert_all_path = '../Preprocessing+baseline/data/ori_pqal.json'
unlabelled_path = '../Preprocessing+baseline/data/ori_pqau.json'


results_root = "./stage2_cv_results_final"

tokenizer = get_tokenizer()

shared_expert_config = {
    "learning_rate": 8e-6,
    "num_train_epochs": 8,
    "train_batch_size": 8,
    "eval_batch_size": 8,
    "gradient_accumulation_steps": 2,
    "use_weighted_loss": False,
    "use_weighted_sampler": True,
    "runs_root": os.path.join(results_root, "runs"),
    "disable_tqdm": False,
    "logging_strategy": "epoch",
    "logging_steps": None,
    "early_stopping_patience": 2,
    "cv_seed": 42,
    "base_seed": 42,
}

advanced_config = {
    **shared_expert_config,
    "teacher_seed_a": 7,
    "teacher_seed_b": 69,
    "student_base_seed": 420,
    "student_learning_rate": 6e-6,
    "student_num_train_epochs": 8,
    "pseudo_multiplier": 2.50,
    "maybe_boost": 1.25,
    "minimum_pseudo_per_class": 20,
    "min_confidence_by_class": {0: 0.78, 1: 0.62, 2: 0.78},
    "min_margin_by_class": {0: 0.12, 1: 0.05, 2: 0.12},
    "base_pseudo_weight": 0.35,
}

In [2]:
# load datasets, build official split, and build outer folds


expert_all = load_expert_json(expert_all_path)
validate_expert_dataset(expert_all)
expert_all = expert_all.map(add_expert_label)
dev_500, test_500 = build_official_500_500_split(expert_all, seed=42)

unlabelled_dataset = load_unlabelled_json(unlabelled_path)

print_labelled_split_summary(dev_500, test_500, title="500 / 500 SPLIT")

outer_folds = build_outer_cv_folds(
    dev_dataset=dev_500,
    n_splits=10,
    seed=shared_expert_config["cv_seed"],
)

print_outer_fold_summary(outer_folds, title="OUTER 10-FOLD CV WITH 400 TRAIN / 50 CALIBRATION / 50 EVALUATION PER FOLD")

========================================================================================
EXPERT DATA CHECK
========================================================================================
Examples      : 1000
Label counts  : {'yes': 552, 'no': 338, 'maybe': 110}
Unique labels : ['maybe', 'no', 'yes']

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

========================================================================================
500 / 500 SPLIT
========================================================================================
dev_500 examples  : 500
dev_500 counts    : {'no': 169, 'maybe': 55, 'yes': 276}

test_500 examples : 500
test_500 counts   : {'no': 169, 'maybe': 55, 'yes': 276}

========================================================================================
OUTER 10-FOLD CV WITH 400 TRAIN / 50 CALIBRATION / 50 EVALUATION PER FOLD
========================================================================================
fold 1
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 6, 'yes': 27}
  eval_50         : 50 | {'no': 17, 'maybe': 5, 'yes': 28}

fold 2
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 6, 'yes': 27}
  eval_50         : 50 | {'no': 17, 'maybe': 5, 'yes': 28}

fold 3
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 6, 'yes': 27}
  eval_50         : 50 | {'no': 17, 'maybe': 5, 'yes': 28}

fold 4
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 6, 'yes': 27}
  eval_50         : 50 | {'no': 17, 'maybe': 5, 'yes': 28}

fold 5
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 6, 'yes': 27}
  eval_50         : 50 | {'no': 17, 'maybe': 5, 'yes': 28}

fold 6
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 5, 'yes': 28}
  eval_50         : 50 | {'no': 17, 'maybe': 6, 'yes': 27}

fold 7
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 5, 'yes': 28}
  eval_50         : 50 | {'no': 17, 'maybe': 6, 'yes': 27}

fold 8
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 5, 'yes': 28}
  eval_50         : 50 | {'no': 17, 'maybe': 6, 'yes': 27}

fold 9
  train_400       : 400 | {'no': 135, 'maybe': 44, 'yes': 221}
  calibration_50  : 50 | {'no': 17, 'maybe': 5, 'yes': 28}
  eval_50         : 50 | {'no': 17, 'maybe': 6, 'yes': 27}

fold 10
  train_400       : 400 | {'no': 136, 'maybe': 44, 'yes': 220}
  calibration_50  : 50 | {'no': 17, 'maybe': 5, 'yes': 28}
  eval_50         : 50 | {'no': 16, 'maybe': 6, 'yes': 28}

In [3]:
# Pipeline S - Simpler supervised baseline

simple_summary = run_simple_pipeline_cv(
    folds=outer_folds,
    stage1_checkpoint_path=stage1_checkpoint_path,
    tokenizer=tokenizer,
    config=shared_expert_config,
)

print()
print("Simpler pipeline mean outer-fold metrics")
for key, value in simple_summary["mean_outer_metrics"].items():
    print(f"  {key}: {value:.4f}")

========================================================================================
PIPELINE S
========================================================================================
Strong supervised baseline. For each outer fold we train on 400 expert examples, calibrate on 50 and report performance on the untouched outer 50.

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=1 | macro_f1=0.6876 | acc=0.7600 | f1_no=0.7778 | f1_maybe=0.4615 | f1_yes=0.8235

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=2 | macro_f1=0.5730 | acc=0.7600 | f1_no=0.8889 | f1_maybe=0.0000 | f1_yes=0.8302

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=3 | macro_f1=0.5465 | acc=0.6800 | f1_no=0.6897 | f1_maybe=0.1429 | f1_yes=0.8070

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=4 | macro_f1=0.5339 | acc=0.6600 | f1_no=0.6061 | f1_maybe=0.2500 | f1_yes=0.7458

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=5 | macro_f1=0.4865 | acc=0.6600 | f1_no=0.6875 | f1_maybe=0.0000 | f1_yes=0.7719

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=6 | macro_f1=0.5623 | acc=0.6400 | f1_no=0.7333 | f1_maybe=0.2500 | f1_yes=0.7037

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=7 | macro_f1=0.6853 | acc=0.7600 | f1_no=0.8125 | f1_maybe=0.4286 | f1_yes=0.8148

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=8 | macro_f1=0.5986 | acc=0.7400 | f1_no=0.7500 | f1_maybe=0.2222 | f1_yes=0.8235

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=9 | macro_f1=0.5794 | acc=0.7200 | f1_no=0.7500 | f1_maybe=0.1667 | f1_yes=0.8214

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=10 | macro_f1=0.5023 | acc=0.7000 | f1_no=0.7273 | f1_maybe=0.0000 | f1_yes=0.7797

Simpler pipeline mean outer-fold metrics
  accuracy: 0.7080
  f1_maybe: 0.1922
  f1_no: 0.7423
  f1_yes: 0.7922
  macro_f1: 0.5755

In [ ]:
# Pipeline E - Advanced semi-supervised expert pipeline

advanced_summary = run_advanced_pipeline_cv(
    folds=outer_folds,
    stage1_checkpoint_path=stage1_checkpoint_path,
    unlabelled_dataset=unlabelled_dataset,
    tokenizer=tokenizer,
    config=advanced_config,
)

print()
print("Advanced pipeline mean outer-fold metrics")
for key, value in advanced_summary["mean_outer_metrics"].items():
    print(f"  {key}: {value:.4f}")

========================================================================================
PIPELINE E
========================================================================================
Advanced semi-supervised pipeline. For each outer fold we train two teachers on 400 expert examples, calibrate them on 50, score the full PQA-U unlabeled pool, select class-aware soft pseudo-labels, train the model, recalibrate it, and report performance on the untouched outer 50.

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1428 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=1 | macro_f1=0.5810 | acc=0.7200 | f1_no=0.7429 | f1_maybe=0.2000 | f1_yes=0.8000 | pseudo=1028

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1428 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=2 | macro_f1=0.6851 | acc=0.8000 | f1_no=0.8750 | f1_maybe=0.3077 | f1_yes=0.8727 | pseudo=1028

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1004 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=3 | macro_f1=0.5214 | acc=0.7600 | f1_no=0.7333 | f1_maybe=0.0000 | f1_yes=0.8308 | pseudo=604

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1428 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=4 | macro_f1=0.5275 | acc=0.6600 | f1_no=0.5882 | f1_maybe=0.2222 | f1_yes=0.7719 | pseudo=1028

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1352 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=5 | macro_f1=0.4724 | acc=0.6600 | f1_no=0.6429 | f1_maybe=0.0000 | f1_yes=0.7742 | pseudo=952

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1396 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=6 | macro_f1=0.4845 | acc=0.7000 | f1_no=0.6667 | f1_maybe=0.0000 | f1_yes=0.7869 | pseudo=996

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1428 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

fold=7 | macro_f1=0.6630 | acc=0.7800 | f1_no=0.7586 | f1_maybe=0.3636 | f1_yes=0.8667 | pseudo=1028

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/400 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/61249 [00:00<?, ? examples/s]

Map:   0%|          | 0/1428 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

In [ ]:
# Compare both pipelines on the development side and choose winner

comparison = compare_pipeline_summaries(
    simple_summary=simple_summary,
    advanced_summary=advanced_summary,
)

winner = comparison["winner"]
loser = comparison["loser"]

print()
print("winner pipeline")
print(f"  {winner['pipeline_name']}")

save_json(simple_summary, os.path.join(results_root, "simple_summary.json"))
save_json(advanced_summary, os.path.join(results_root, "advanced_summary.json"))
save_json(comparison, os.path.join(results_root, "pipeline_comparison.json"))

In [ ]:
# official test result for the winning pipeline

winning_config = shared_expert_config if winner["pipeline_name"] == "simple_supervised" else advanced_config

winning_test_result = run_final_test_committee(
    pipeline_name=winner["pipeline_name"],
    stage1_checkpoint_path=stage1_checkpoint_path,
    dev_500=dev_500,
    test_500=test_500,
    tokenizer=tokenizer,
    config=winning_config,
    unlabelled_dataset=unlabelled_dataset if winner["pipeline_name"] == "advanced_ssl" else None,
)

save_json(winning_test_result, os.path.join(results_root, "winning_test_result.json"))